---
title: "baseball_R"
output:
  github_document:
    html_preview: true
---

Companion to *Analyzing Baseball Data with R*, 2nd edition.

- Official book page: http://www.crcpress.com/product/isbn/9781466570221
- Book's blog: http://baseballwithr.wordpress.com/

Instructions
------------

In order to have a working copy of the code in the book, download the zip file of this repository and extract the content of the zip file in a folder of your convenience.

- The `data` folder contains datasets used in the book, except those downloadable from websites, and those that are too large to store on GitHub (e.g., the full season Statcast files). In order to get the missing datasets, read the `readme.txt` files stored inside the `lahman`, `sqldumps` and `wizardry` subfolders of the `data` folder.
- The `scripts` folder contains standalone R scripts that were referenced in the text. 
- The `chapter_code` folder contains all of the code that was written to generate each chapter. (e.g., the result of running `knitr::purl()` on each of the chapter source files.)


Last updated: ```r format(Sys.Date(), "%B %e, %Y")```